Vagrant.configure("2") do |config|
    config.vm.provider "virtualbox" do |vm|
    config.vm.synced_folder "./ansible", "/ansible"  
    config.vm.provision "shell", inline: <<-SHELL
      apt-get update
      apt-get install -y ansible
      ansible-playbook --connection=local /ansible/playbook.yml
    SHELL
      vm.memory = 2048
      vm.cpus = 2
    end
    config.vm.box = "ubuntu/focal64"
    config.vm.network "public_network", ip: "192.168.0.61"
    config.vm.network "forwarded_port", guest: 80, host: 8080
  end 